apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-sender
spec:
  selector:
    matchLabels:
      app: eventhub-sender
  template:
    metadata:
      labels:
        app: eventhub-sender
    spec:
      containers:
      - name: eventhub-sender
        image: sparkeventhubstreaming:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
